### ISSUE TITLE
Documentation still mentions images URLs as an option

### ISSUE THREAD

**Issue by nicorikken** [lf-energy/lfenergy-landscape#294]
According to the readme one should be able to submit a image URL. Turns out that triggers a build error, as in https://github.com/lf-energy/lfenergy-landscape/pull/293 So the README could use an update. Perhaps there is more current documentation in the CNCF-landscape repo that can be adopted?

**Comment by jmertic** [comment]
@nicorikken - Review the updated page and let me know if that addresses your issue.

**Comment by nicorikken** [comment]
Nope, I see that it is still there:
> If you think your project should be included, please open a pull request to add it to landscape.yml. For the logo, you can either upload an SVG to the hosted_logos directory or put a URL as the value, and it will be fetched.
I shall open a PR.

**Comment by jmertic** [comment]
Somehow missed that - fixed now.

**Comment by nicorikken** [comment]
Nice, I was working on a PR, you beat me to it. Great!
