### ISSUE TITLE
Update Landscape Entry for [CIMtool]

### ISSUE THREAD

**Issue by Sander3003** [lf-energy/lfenergy-landscape#440]
### Changes requested

This a better repository to refer: https://github.com/CIMug-org/CIMTool (the current one is out of date).

Organisation behind it: https://cimug.ucaiug.org/

**Comment by jmertic** [comment]
Fixed by https://github.com/lf-energy/lfenergy-landscape/commit/14c0157061ec67fb0f435b71a08ddbe4dd731bee
