### ISSUE TITLE
Update Landscape Entry for OpenEEmeter

### ISSUE THREAD

**Issue by philngo-recurve** [lf-energy/lfenergy-landscape#749]
### Changes requested

**Technical Summary (max 100 words):**

The OpenEEmeter is a library of software packages and supporting methods documentation for computing consistent and replicable estimates of changes in time series of energy consumption, primarily as measured for populations of commercial and residential buildings. The OpenEEmeter emphasizes consistency and replicability to facilitate payments and market transactions that may be take the energy savings outputs of the software as inputs.

**Top Use Cases (max 3)**:

- Computes revenue-grade impacts of residential and commercial demand flexibility, such as energy efficiency projects, behavioral interventions, and demand-response events.
- Documents standard approaches and reasoning behind methodological approaches to data modeling.
- Supports methods development and model testing.

**Latest release info (including link)**:

Latest releases can be found in the changelog: https://github.com/openeemeter/eemeter/blob/master/CHANGELOG.md

**Link to architectural overview diagram**:

No architectural overview diagram available - here is a link to a tutorial. https://eemeter.openee.io/tutorial.html

**Comment by jmertic** [comment]
@yarille for the HL overview deck.

**Comment by yarille** [comment]
Slides created
