### ISSUE TITLE
Update Landscape Entry for Power Grid Model

### ISSUE THREAD

**Issue by TonyXiang8787** [lf-energy/lfenergy-landscape#750]
### Changes requested

# Technical Summary (max 100 words)

Power Grid Model (`power-grid-model` and `power-grid-model-io`) is a high performance distribution grid calculation model. It has a C++ calculation core with a mature C-API and Python API. Currently, it supports the following calculations:

* Symmetric and asymmetric power flow calculation with Newton-Raphson method, iterative current method and linear method
* Symmetric and asymmetric state estimation with iterative linear method

# Top Use Cases (max 3)

* Short term real-time state estimation and forecasting
* Long term grid planning
* Congestion management

# Latest release info (including link)

Power Grid Model uses rolling release. Every merge to the `main` branch will trigger the CI pipeline to build and publish a new version. See below the list of releases:

https://github.com/alliander-opensource/power-grid-model/releases

# Link to architectural overview diagram

See below the link to the documentation including the architectural overview.

https://power-grid-model.readthedocs.io/en/stable/

**Comment by jmertic** [comment]
@yarille This is for the HL overview deck FYI. We might want to consider incorporating into the landscape at some point.

**Comment by yarille** [comment]
@jmertic I made a note to do this. Slide created.
