### ISSUE TITLE
Update Landscape Entry for FlexMeasures

### ISSUE THREAD

**Issue by nhoening** [lf-energy/lfenergy-landscape#751]
### Changes requested

# Technical Summary 

When we use a lot of renewable energy, flexibility is becoming crucial and valuable, e.g. for demand response. FlexMeasures is the intelligent & developer-friendly EMS to support real-time energy flexibility apps, rapidly and scalable.

FlexMeasures is a real-time decision support platform (project operation), but also highly effective as a simulation tool (project design).

The problem it helps to solve is: What are the best times to run flexible assets, like batteries, heat pumps or industry processes?

In a nutshell, FlexMeasures turns data into optimized schedules for flexible assets.

# Top Use Cases

1. Industry: Shift process running times to minimize balancing costs as well as CO2 & support network congestion
2. Built Environment: Optimize heating to satisfy comfort and energy costs (use rooftop solar & dynamic tariffs)
3. E-Mobility (optimal charging time to lower bills, including vehicle-to-grid)

The FlexMeasures project is thriving towards sector-coupling, that is, to optimize different flexible energy use together. For example, scheduling both heat pumps and EV charging.

# Latest release info

Version v0.12 of FlexMeasures adds a cool re-play feature and support for adding custom scheduling algorithms.

Release info & downloads:

- https://flexmeasures.io/012-replay-custom-scheduling/
- https://pypi.org/project/flexmeasures/0.12.2/
- https://github.com/FlexMeasures/flexmeasures/releases/tag/v0.12.2

# Link to architectural overview diagram

https://www.lfenergy.org/wp-content/uploads/sites/67/2022/04/overview-flexEMS-1024x586.png

**Comment by yarille** [comment]
slide updated
