### ISSUE TITLE
Update Landscape Entry for [OpenSTEF]

### ISSUE THREAD

**Issue by FrankKr** [lf-energy/lfenergy-landscape#752]
### Changes requested

•	Technical Summary ( max 100 words )
OpenSTEF is a software stack that predicts future load on the electricity grid using machine learning. It works with energy consumption, renewable generation, or a combination of both. OpenSTEF validates input data, uses external predictors such as weather and market prices, trains machine learning models, and provides a forecast via API and graphical user interface. The stack is based on open source technology, organized in a microservice architecture, and optimized for cloud-deployment.
•	Top Use Cases ( max 3 )
- Forecasting load at the DSO/TSO interface
- Forecasting load for the DSO to perform congestion management
- Forecasting load on secondary substations or individual customers to facilitate smart-grid applications
•	Latest release info ( including link )
https://openstef.github.io/openstef/index.html
•	Link to architectural overview diagram
https://openstef.github.io/openstef/concepts.html

**Comment by yarille** [comment]
Slide updated
