### ISSUE TITLE
Update Landscape Entry for [PROJECT]

### ISSUE THREAD

**Issue by watare** [lf-energy/lfenergy-landscape#754]
### Changes requested

The energy sector is following the telecommunications field by moving towards virtualization for increased flexibility and cost reduction. This leads to an IT/OT convergence where critical applications, previously hosted on specific hardware, become virtual machines. However, these applications require high availability, real-time performance, and cybersecurity.

SEAPATH is a project under the LF Energy umbrella that provides a solution for building a real-time virtualization industrial-grade platform based on Yocto or Debian. The technology behind SEAPATH includes the use of Ceph storage, Linux RT, Pacemaker for high availability, Open vSwitch (OVS) for network virtualization, SR-IOV for hardware acceleration, KVM for virtualization, and PTP synchronization for accurate timekeeping

The SEAPATH project can be used: 

- By vendors to build a fully virtualized digital substation and ensured to its client that it is based on open source
- By integrators that wants to propose and support a real-time virtualization industrial-grade platform for their clients
- By utilities, universities and start up that want to evaluate their concepts and take benefit of this collaboration framework

Recently the SEAPATH project has made big evolutions regarding testing and hardening:

- [testing/ci](https://github.com/seapath/ci)
- [debian hardening](https://github.com/seapath/ansible/commits/debian-main)

Want to build your SEAPATH cluster? You should start [here](https://github.com/seapath/seapath-architecture)

**Comment by yarille** [comment]
slide updated
