### ISSUE TITLE
Update Landscape Entry for [PROJECT]

### ISSUE THREAD

**Issue by stenoo83** [lf-energy/lfenergy-landscape#793]
### Changes requested

Please update your Sense Reply tab

Organization: Sense Reply srl

Website: https://www.reply.com/sense-reply/en/

Linkedin https://www.linkedin.com/company/sense-reply/

Twitter https://twitter.com/Reply_ITA

Headquarter 
Rome
Via del Giorgione, 59
00147 Rome, Italy
Tel: +39 06 844341
Fax: +39 06 84434599

**Comment by jmertic** [comment]
Hi - thanks for this @stenoo83. We added a Crunchbase entry for Sense Reply with these details, and linked it to the Landscape entry card. See a preview below - let us know if this works for you.

https://deploy-preview-794--lfenergy.netlify.app/members?selected=sense-reply-member
