### ISSUE TITLE
New Landscape Entry - Interactive Power Flow (IPF)

### ISSUE THREAD

**Issue by mbheinen** [lf-energy/lfenergy-landscape#809]
### Project Name

Interactive Power Flow (IPF)

### Description

Interactive Power Flow (IPF) is a software package for doing power flow studies. IPF models the operation of a bulk electric power network. IPF was developed by [Bonneville Power Administration](https://www.bpa.gov/) (BPA) and its contractors in the 1990s with about 20% of the cost supported by the [Electric Power Research Institute](https://www.epri.com/) (EPRI). By mutual agreement, as described in EPRI Agreement RP2746-03 entitled Graphical User Interface for Powerflow, March, 1992,

“all results of this project–including the computer program and its documentation–are to be in the public domain.”

While not a modern tool (written in Fortran and uses X Window for displays/UI), it can still be used for benchmarking new power flow engines and transient stability analysis tools.

### Homepage URL

https://bpa-ipf.readthedocs.io/en/latest/index.html

### Repo URL

https://github.com/mbheinen/bpa-ipf-tsp

### Organization hosting or owning the project

Bonneville Power Administration (original creator)

### Logo

![IPF-Bus](https://github.com/lf-energy/lfenergy-landscape/assets/6753163/5ec6fb83-3d13-488b-ba7e-29e5fca2e3db)

Category is really "Energy Systems - Modeling and Simulation" but non of dropdown categories really fit that so I just put "Asset Management - Analytics" even though IPF really isn't that

### Category

Asset Management - Analytics

**Comment by jmertic** [comment]
Thank you, @mbheinen! Look at the entry below and let me know if this looks correct.

https://deploy-preview-811--lfenergy.netlify.app/?selected=interactive-power-flow-ipf

Note we added the project name to the logo; this is a general standard for the landscape to help people better identify the project in the logo view.

**Comment by jmertic** [comment]
I've also update the form to have the new correct categories in place - thank you for alerting me to that!

**Comment by mbheinen** [comment]
Logo looks good. IPF has never had a logo so I just made one up and I
figured I wanted to use *something *from the original project by Bonneville
so I went with the only icon like image I could find which was on this
"bus" display
https://bpa-ipf.readthedocs.io/en/latest/basic/x_window_gui.html#ac-bus-input-data-boxes
.

**Comment by jmertic** [comment]
Awesome - thanks! Merging now.
