### ISSUE TITLE
Update Landscape Entry for Utilidata

### ISSUE THREAD

**Issue by dbrownlf** [lf-energy/lfenergy-landscape#824]
### Changes requested

Please update the logo for LF Energy member Utilidata as they have just completed a rebranding. New logo is attached.
![Utilidata Logo Lockup Black](https://github.com/lf-energy/lfenergy-landscape/assets/120492450/0a6905f7-84d7-4323-a8fe-14c6187e14c5)

**Comment by jmertic** [comment]
Hey @dbrownlf - these changes should be made in Org Dashboard - can you update there?
