### ISSUE TITLE
Checkout main fails

### ISSUE THREAD

**Issue by jkiviluo** [lf-energy/lfenergy-landscape#827]
### Thank you for providing feedback on improving the LF Energy Landscape. Please update the title above and add your feedback below

On Windows 10:

```
C:\data\other_software\lfenergy-landscape>git checkout main
error: invalid path 'hosted_logos/Data wrangling for the "IEA Net Zero by 2050" Roadmap.svg'
```

This was after `git clone`, which also failed on same error.

**Comment by jmertic** [comment]
Good catch! I think this commit should fix it; can you confirm?

https://github.com/lf-energy/lfenergy-landscape/commit/b7d17353b24a060938c7ab74556eb6489dd14f58

**Comment by jkiviluo** [comment]
Yes, it fixes it. Although I had to clone the repo again. Apparently the issue broke the .git directory and at least I didn't know how to recover that.
