### ISSUE TITLE
New Landscape Entry - Backbone

### ISSUE THREAD

**Issue by jkiviluo** [lf-energy/lfenergy-landscape#831]
### Project Name

Backbone

### Description

Backbone is a generic energy network optimization tool written in [GAMS](https://www.gams.com/) for both planning and operations. It has been designed to be highly adaptable in different dimensions: temporal, spatial, technology representation and market design. The model can represent both short-term forecasts and longer-term statistical uncertainties. Backbone can support multiple different models due to the modifiable temporal structure and varying lengths of the time steps.

### Homepage URL

https://gitlab.vtt.fi/backbone/backbone/-/wikis/home

### Repo URL

https://gitlab.vtt.fi/backbone/backbone

### Organization hosting or owning the project

VTT Technical Research Centre of Finland

### Logo

![backbone_logo](https://github.com/lf-energy/lfenergy-landscape/assets/40472544/9f54dfee-8c08-4364-b354-70f21f5026bb)

### Category

Energy Systems - Modeling and Optimization

**Comment by jmertic** [comment]
Hey @jkiviluo - we have this one in there at https://landscape.lfenergy.org/?selected=backbone

But - we don't have a nice logo :-(. Can you provide a higher qualify version of the logo you attached?

**Comment by jkiviluo** [comment]
Right. Backbone is in the wrong category though. It should be in Modeling and Optimization. It can do simplified distribution grid modelling, but the main focus is on transmission level and energy system modelling.

Here's a higher resolution logo:
![backbone_logo_large](https://github.com/lf-energy/lfenergy-landscape/assets/40472544/39b9b543-5ce6-4247-9997-2d3440cb8cf7)

**Comment by jmertic** [comment]
Got it - fixed at https://github.com/lf-energy/lfenergy-landscape/commit/fbe69a146471b91f601237d24dfd6554b85bc9c8. Thanks!
