### ISSUE TITLE
Update Landscape Entry for mosaik

### ISSUE THREAD

**Issue by eike** [lf-energy/lfenergy-landscape#852]
### Changes requested

Change the license to Open Source (mosaik is licensed under LGPL, see the repository here: https://gitlab.com/mosaik/mosaik, most of the adapters are licensed under MIT).

Thank you!
Greetings from the mosaik team

**Comment by jmertic** [comment]
Hi - thanks for this update @eike ! Can you take a look and see if this card looks correct to you?

https://deploy-preview-853--lfenergy.netlify.app/card-mode?selected=mosaik

**Comment by eike** [comment]
Oh, sorry, I was imprecise in my original post. mosaik is licensed under LGPL 2.1, not LGPL 3.0. Other than that, it looks good. Thanks!

**Comment by jmertic** [comment]
No worries - check now to see if it's correct.

**Comment by eike** [comment]
Yes, perfect. Thank you!
