### ISSUE TITLE
New Landscape Entry - [FAME]

### ISSUE THREAD

**Issue by dlr-cjs** [lf-energy/lfenergy-landscape#870]
### Project Name

FAME

### Description

FAME is the open **F**ramework for distributed **A**gent-based **M**odels of **E**nergy systems. Its purpose is supporting the rapid development and fast execution of complex agent-based simulations in the energy systems domain. Please find details in two articles describing FAME's two main components: [FAME-Core](https://joss.theoj.org/papers/10.21105/joss.05087) and [FAME-Io](https://joss.theoj.org/papers/10.21105/joss.04958).

### Homepage URL

https://gitlab.com/fame-framework/wiki/-/wikis/home

### Repo URL

https://gitlab.com/fame-framework

### Organization hosting or owning the project

Deutsches Zentrum für Luft- und Raumfahrt e.V.

### Logo

![DLR_Logo_FAME_Squared](https://github.com/lf-energy/lfenergy-landscape/assets/89577600/ce323dd6-0225-4111-8b4f-7eaba391beab)

### Category

Energy Systems - Modeling and Optimization

**Comment by jmertic** [comment]
Thank you for submitting this! Do you have a version of the logo in an SVG format?

**Comment by dlr-cjs** [comment]
> Thank you for submitting this! Do you have a version of the logo in an SVG format?

Unfortunately, we only have .png or .jpg or available.

**Comment by jmertic** [comment]
Ah bummer! Do you have a higher quality version than earlier submitted? I can try to trace it to SVG.

**Comment by jmertic** [comment]
That works - take a look at the preview at the link below and let me know if it all looks right...

https://deploy-preview-871--lfenergy.netlify.app/?selected=fame

**Comment by dlr-cjs** [comment]
Cool, looks fine for me. Do you require additional information on the German Aerospace Center or are these extracted from a database? I saw "Headquarters" and "Headcount" listed in other entries...

**Comment by jmertic** [comment]
Sure - I linked in the Crunchbase entry - let me know if this looks right...

https://deploy-preview-871--lfenergy.netlify.app/card-mode?selected=fame

**Comment by dlr-cjs** [comment]
Perfect. Thank you
