### ISSUE TITLE
New Landscape Entry - [AMIRIS]

### ISSUE THREAD

**Issue by dlr-cjs** [lf-energy/lfenergy-landscape#873]
### Project Name

AMIRIS

### Description

AMIRIS is the open **A**gent-based **M**arket model for the **I**nvestigation of **R**enewable and **I**ntegrated energy **S**ystems. It aims at enabling scientists to dissect the complex questions arising with respect to future energy markets, their market design, and energy-related policy instruments. The model computes electricity prices endogenously based on the simulation of strategic bidding behavior of prototyped market actors. This bidding behavior does not only reflect marginal prices, but can also consider effects of support instruments like market premia, uncertainties and limited information, or market power.

### Homepage URL

https://dlr-ve.gitlab.io/esy/amiris/home/

### Repo URL

https://gitlab.com/dlr-ve/esy/amiris/amiris

### Organization hosting or owning the project

Deutsches Zentrum für Luft- und Raumfahrt e.V.

### Logo

![DLR_Logo_AMIRIS_Schriftunten](https://github.com/lf-energy/lfenergy-landscape/assets/89577600/1c25a0c0-fb97-483a-aa6a-b5ff55f55dfa)

### Category

Energy Systems - Modeling and Optimization

**Comment by jmertic** [comment]
Hi @dlr-cjs - thank you for submitting this! Check out the entry below and let me know what you think...

https://deploy-preview-875--lfenergy.netlify.app/?selected=amiris

**Comment by dlr-cjs** [comment]
Thank you, looks perfect to me.

**Comment by jmertic** [comment]
Great! Merging in now. Thank you!
