### ISSUE TITLE
Update Landscape Entry for [GHEtool]

### ISSUE THREAD

**Issue by wouterpeere** [lf-energy/lfenergy-landscape#878]
### Changes requested

Hi! I noticed GHEtool was on the LF energy landscape, thanks!
However, some of the information is not quite correct, since the tool is no longer updated by the university. Please find below the requested changes.

website: https://ghetool.eu
linked-in: https://linkedin.com/company/ghetool
twitter/X: not existing
headquarters: Waregem/Belgium
crunchbase: not existing

**Comment by jmertic** [comment]
Thank you @wouterpeere! Please take a look at the preview below and let me know if it looks accurate...

https://deploy-preview-879--lfenergy.netlify.app/card-mode?selected=gh-etool

**Comment by wouterpeere** [comment]
Hi @jmertic , perfect, thanks!
Later this year, we will do a major restructuring, but I'll inform you later on that one!

**Comment by jmertic** [comment]
Sounds great - thanks!
