### ISSUE TITLE
New Landscape Entry - RiseClipse

### ISSUE THREAD

**Issue by ADehouck** [lf-energy/lfenergy-landscape#882]
### Project Name

RiseClipse

### Description

RiseClipse is an umbrella name for tools based on MDE technologies and dedicated to IEC standards. Open source RiseClipse components are availble under the EPL version 2.0.
The main use of RiseClipse is to validate IEC CIM files and IEC 61850 SCL configuration files : data described in these files are loaded in a way to become conformant with an UML model (either the CIM UML model or the SCL one), and OCL (Object Constraint Language) is used for validation. Therefore, the validation is not only done at the syntactic level but also at the semantic level. 

### Homepage URL

https://riseclipse.github.io/

### Repo URL

https://github.com/riseclipse

### Organization hosting or owning the project

EDF and CentraleSupélec

### Logo

![Logo RiseClipse - Copie](https://github.com/lf-energy/lfenergy-landscape/assets/62877587/563a91c2-68ca-464f-9c4d-c75aa4fb1c98)

### Category

Energy Systems - Modeling and Optimization

**Comment by jmertic** [comment]
Thank you @ADehouck - can you review the entry preview below and let me know if it's good to add?

https://deploy-preview-883--lfenergy.netlify.app/?selected=rise-clipse

**Comment by ADehouck** [comment]
Thank you @jmertic !

Just some small comments:
* You mentionned "EDF Group", could you also add "CentraleSupélec" please ? it is shared between these 2 organizations
* Could you change the linkedIn to this one: www.linkedin.com/in/riseclipse-2b8b8318a
* Could you change the (primary) repository to "riseclipse-validator-scl2003" instead of "riseclipse-ocl-constraints-scl2003"
* I am surprised that the latest commit is "2 years ago", maybe it corresponds to the activity of the project "riseclipse-ocl-constraints-scl2003",  when you will change the primary repo to "riseclipse-validator-scl2003", maybe the lastest commit will update to "last week" ?
* I don't know if you would also like to add the dockerHub link ? https://hub.docker.com/u/riseclipse

Best regards,
Aurélie

**Comment by jmertic** [comment]
Hi - see responses inline...

> You mentionned "EDF Group", could you also add "CentraleSupélec" please ? it is shared between these 2 organizations

We can only tag one organization as an owner. I would suggest whomever is the majority owner be the organization listed here, or the project create a Crunchbase entry for itself.

> Could you change the linkedIn to this one: [www.linkedin.com/in/riseclipse-2b8b8318a](http://www.linkedin.com/in/riseclipse-2b8b8318a)

We can only point to LinkedIn organization profiles, not individual ones like that one is.

> Could you change the (primary) repository to "riseclipse-validator-scl2003" instead of "riseclipse-ocl-constraints-scl2003"

Yep., done!

> I am surprised that the latest commit is "2 years ago", maybe it corresponds to the activity of the project "riseclipse-ocl-constraints-scl2003", when you will change the primary repo to "riseclipse-validator-scl2003", maybe the lastest commit will update to "last week" ?

That change did adjust the last commit date, so all good there

> I don't know if you would also like to add the dockerHub link ? https://hub.docker.com/u/riseclipse

Added that now. Thanks!

**Comment by ADehouck** [comment]
Hello @jmertic ,

Thank you for your updates, it is OK for me to add like this,

Best regards,
Aurélie
