### ISSUE TITLE
GidCal - The one stop shop for power systems planning

### ISSUE THREAD

**Issue by SanPen** [lf-energy/lfenergy-landscape#887]
### Project Name

GidCal

### Description

GridCal, a cross-platform power systems software written in Python with user interface, used in academia and industry. 
GridCal does all sort of static analysis of power systems with or without time series (power flow, short circuit, linear and non linear optimization, ..., you name it)

### Homepage URL

https://github.com/SanPen/GridCal

### Repo URL

https://github.com/SanPen/GridCal

### Organization hosting or owning the project

https://www.advancedgridinsights.com/

### Logo

![GridCal_round_icon](https://github.com/lf-energy/lfenergy-landscape/assets/13423311/4991cc4e-b974-4cac-a0c8-c52cdab5d75c)

### Category

Energy Systems - Modeling and Optimization

**Comment by jmertic** [comment]
Hi! We have an entry for GridCal at https://landscape.lfenergy.org/card-mode?selected=grid-cal - I can update the logo if you'd like.

**Comment by SanPen** [comment]
Hi John!
Thanks for noticing, could we update the logo, the category and URL's?

**Comment by jmertic** [comment]
Sure thing! Take a look at the preview below...

https://deploy-preview-889--lfenergy.netlify.app/card-mode?selected=grid-cal

The one slight change is the logo, we request a logo with the project name in it and in SVG format; I found this one below that meets those requirements - let me know if it's ok or if we should rebase off the logo provided...

**Comment by SanPen** [comment]
This looks good!

**Comment by jmertic** [comment]
Excellent - thank you! Will push out the update now.
